theme: minima
title: Alex's wall of posts
author: AlexHwit
email: contact@alexanderhwit.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Alex's wall of posts streaming from his brain, just here to feed knowledge to brain.

# social links
twitter_username: alexanderhwit # DO NOT include the @ character, or else the build will fail!
github_username:  AlexHwit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
